# Generated by Django 5.2.7 on 2025-12-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_box',
            field=models.BooleanField(default=False),
        ),
    ]
